src/main/java/br/com/tutorial/springmvc/model/Gift.java
package br.com.tutorial.springmvc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ForeignKey;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

@Entity
@Table(name="gift")
public class Gift {
	
	@SuppressWarnings("unused")
	private static final long serialVersionUID = 1L;
	@Id @Generated(GenerationTime.INSERT) 
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id", unique=true) 
	private long id;

    @ManyToOne
    @ForeignKey(name="product_fk")
	private Product product;
	
	private String email;
	
	private String creditcard;
	
	private String secureCode;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCreditcard() {
		return creditcard;
	}

	public void setCreditcard(String creditcard) {
		this.creditcard = creditcard;
	}

	public String getSecureCode() {
		return secureCode;
	}

	public void setSecureCode(String secureCode) {
		this.secureCode = secureCode;
	}

}

src/main/java/br/com/tutorial/springmvc/model/Product.java
package br.com.tutorial.springmvc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

@Entity
@Table(name="product")
public class Product {
	
	private static final long serialVersionUID = 1L;
	@Id @Generated(GenerationTime.INSERT) 
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id", unique=true) 
	private long id;
	private String name;
	private String description;
	private String style;
	private int month;
	private int year;
	private String price;
	private String url;

	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getStyle() {
		return style;
	}
	public void setStyle(String style) {
		this.style = style;
	}
	public int getMonth() {
		return month;
	}
	public void setMonth(int month) {
		this.month = month;
	}
	public int getYear() {
		return year;
	}
	public void setYear(int year) {
		this.year = year;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	public String getPrice() {
		return price;
	}
	public void setPrice(String price) {
		this.price = price;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}	
	public String getPriceWithoutFormat() {
		String value = this.getPrice();
		return value.substring(3, value.length());
	}
	
}

src/main/java/br/com/tutorial/springmvc/controller/admin/GiftController.java
package br.com.tutorial.springmvc.controller.admin;

import java.security.Principal;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import br.com.tutorial.springmvc.dao.DAOGift;
import br.com.tutorial.springmvc.dao.DAOProduct;
import br.com.tutorial.springmvc.model.Gift;
import br.com.tutorial.springmvc.model.Product;

@Controller
public class GiftController {

	public static String EMPTY_VALUE = "NULLVALUE";

	public static String USERNAME_EXIST = "USERNAMEEXIST";

	public static String CORRECT = "OK";

	@Autowired
	private DAOGift daoGift;
	
	@Autowired
	private DAOProduct daoProduct;

	@ModelAttribute("giftBuy")
	public Gift create() {
		return new Gift();
	}

	@RequestMapping(value = "/gift", method = RequestMethod.GET)
	public ModelAndView giftToSomebody(
			@ModelAttribute("giftBuy") Gift gift) {
		ModelAndView m = new ModelAndView();
		m.setViewName("gift");
		return m;
	}

	@RequestMapping(value = "/gift/{id}", method = RequestMethod.GET)
	public String edit(@PathVariable("id") long id, @ModelAttribute("giftBuy") Gift giftBuy,
			RedirectAttributes redirectAttributes) {
		Product product = daoProduct.get(id);
		redirectAttributes.addFlashAttribute("productRegistration", product);
		return "redirect:/gift";
	}

	@RequestMapping(value = "/gift", method = RequestMethod.POST)
	public String add(@Valid Gift gift, BindingResult result, Model model,
			Principal principal) {
		boolean go = false;
		if (gift.getCreditcard().isEmpty() || gift.getEmail().isEmpty()
				|| gift.getProduct() == null || gift.getSecureCode().isEmpty()) {
			go = false;
		} else {
			go = true;
		}

		if (!go) {
			return "redirect:/createEmptyAccount";
		} else {
			Product product = daoProduct.get(gift.getProduct().getId());
			gift.setProduct(product);
			daoGift.save(gift);
			return "redirect:/createMessageAccount";
		}
	}

}

src/main/java/br/com/tutorial/springmvc/controller/physician/LoginController.java
package br.com.tutorial.springmvc.controller.physician;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class LoginController {

	@RequestMapping("/login")
	public String redirect() {
		return "login";
	}
	
	@RequestMapping("/loginfailed")
	public String logout() {
		return "loginfailed";
	}


}

src/main/webapp/views/index.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
    <!-- Page Specific CSS -->
    
    <style>
    .texto-index{padding-top: 36px;
				text-align: center;
				letter-spacing: 2px;}
				
	h1{color: #49d1c6;
	   text-align: center;}		
	   	
    </style>
    

    <div>
    </div> 		

src/main/webapp/views/listStyle.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<link rel="shortcut icon" href="<c:url value="/images/favicon.ico"/>"
	type="image/x-icon">
<link rel="icon" href="<c:url value="/images/favicon.ico"/>"
	type="image/x-icon">

<title>Yudi Games</title>

<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="<c:url value="/css/bootstrap.min.css"/>">


<!-- Custom CSS -->
<link rel="stylesheet" href="<c:url value="/css/shop-homepage.css"/>">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a href="/springmvc/"> <img alt="Yudi Games"
					src="<c:url value="images/icone.png"/>">
				</a>
			</div>
			</br> </br>
			<div style="text-align: right;">
				<a href="createAccount" style="color: #fff">Criar conta</a> <span
					style="color: #fff">|</span> <a href="premiumAccount"
					style="color: #fff">Conta Premium</a>
			</div>

		</div>
		<!-- /.container -->
	</nav>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<div class="col-md-3">
				<br> <br>
				<p class="lead">Categorias</p>
				<div class="list-group">
					<a href="<c:url value="listProductToSite/RPG"/>"
						class="list-group-item">RPG</a> <a
						href="<c:url value="listProductToSite/ACAO"/>"
						class="list-group-item">Ação</a> <a
						href="<c:url value="listProductToSite/OUTROS"/>"
						class="list-group-item">Outros</a>
				</div>
			</div>

			<div class="col-md-9">

				<div class="row carousel-holder">

					<div class="col-md-12">
						<div id="carousel-example-generic" class="carousel slide"
							data-ride="carousel">
							<ol class="carousel-indicators">
								<li data-target="#carousel-example-generic" data-slide-to="0"
									class="active"></li>
								<li data-target="#carousel-example-generic" data-slide-to="1"></li>
								<li data-target="#carousel-example-generic" data-slide-to="2"></li>
							</ol>
							<div class="carousel-inner">
								<div class="item active">
									<a href="#"> <img class="slide-image"
										src="http://rafaeltome.dominiotemporario.com/scrummaster/banner/final_fantasy.png"
										alt="">
									</a>
								</div>
								<div class="item">
									<a href="#"> <img class="slide-image"
										src="http://rafaeltome.dominiotemporario.com/scrummaster/banner/street_figther.png"
										alt="">
									</a>
								</div>
								<div class="item">
									<a href="#"> <img class="slide-image"
										src="http://rafaeltome.dominiotemporario.com/scrummaster/banner/tomb_raider.png"
										alt="">
									</a>
								</div>
							</div>
							<a class="left carousel-control" href="#carousel-example-generic"
								data-slide="prev"> <span
								class="glyphicon glyphicon-chevron-left"></span>
							</a> <a class="right carousel-control"
								href="#carousel-example-generic" data-slide="next"> <span
								class="glyphicon glyphicon-chevron-right"></span>
							</a>
						</div>
					</div>

				</div>

				<div class="row">

					<c:forEach var="product" items="${productList}">
						<div class="col-sm-4 col-lg-4 col-md-4">
							<div class="thumbnail">
								<img
									src="http://rafaeltome.dominiotemporario.com/scrummaster/${product.url}">
								<div class="caption">
									<h4 class="pull-right">${product.price}</h4>
									<h4>
										<a href="#">${product.name}</a>
									</h4>
									<p>${product.description}
									<div>
										<a href="gift/${product.id}">
											<button type="button" class="btn btn-default pull-right">
												<img alt="Yudi Games" src="images/gift.png" width="16"
													height="16" />
											</button>
										</a>
										<form target="pagseguro" method="post"
											action="https://pagseguro.uol.com.br/checkout/checkout.jhtml">
											<input type="hidden" name="email_cobranca"
												value="rafaeltsouza@terra.com.br" /> <input type="hidden"
												name="tipo" value="CBR" /> <input type="hidden"
												name="moeda" value="BRL" /> <input type="hidden"
												name="item_id" value="${product.id}" /> <input
												type="hidden" name="item_descr" value="${product.name}" />
											<input type="hidden" name="item_quant" value="1" /> <input
												type="hidden" name="item_valor"
												value="${product.priceWithoutFormat}" /> <input
												type="hidden" name="frete" value="0" /> <input
												type="hidden" name="peso" value="0" /> <input type="image"
												name="submit"
												src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/99x61-comprar-assina.gif"
												alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
										</form>

										<!-- 
										<button type="button" class="btn btn-default pull-right" aria-label="Left Align">
											<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> 
											<a href="#">Comprar</a>
										</button>  
										<button type="button" class="btn btn-default pull-right">
											<a href="gift/${product.id}"><img alt="Yudi Games" src="images/gift.png" width="16" height="16"></a>
										</button>
										 -->

									</div>
									</p>
								</div>
							</div>
						</div>
					</c:forEach>

				</div>

			</div>

		</div>
	</div>

	</div>
	<!-- /.container -->

	<div class="container">

		<hr>

		<!-- Footer -->
		<footer>
			<div class="row">
				<div class="container">
					<p>Copyright &copy; Yudi Games 2015</p>
				</div>
			</div>
		</footer>

	</div>
	<!-- /.container -->

	<!-- jQuery -->
	<script src="<c:url value="/js/jquery.js"/>"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="<c:url value="/js/bootstrap.min.js"/>"></script>
</body>

</html>

src/main/webapp/views/login.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <!-- Title and other stuffs -->
  <title>Spring MVC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

<!-- Form area -->
<div class="admin-form">
  <div class="container">

    <div class="row">
      <div class="col-md-5">
        <!-- Widget starts -->
            
            <div class="widget worange">
              <!-- Widget head -->

              <div class="widget-head">
                Login
              </div>

              <div class="widget-content">
                <div class="padd">
                  <!-- Login form -->
				  <form class="form-horizontal" action="<c:url value="/j_spring_security_check"/>" method="post">
                    <!-- Email -->
                    <div class="form-group">
                      <label class="control-label col-lg-3" for="username">Username</label>
                      <div class="col-lg-9">
                        <input class="form-control" placeholder="Username" name="j_username" id="username">
                      </div>
                    </div>
                    <!-- Password -->
                    <div class="form-group">
                      <label class="control-label col-lg-3" for="password">Password</label>
                      <div class="col-lg-9">
                          <input type="password" class="form-control" id="password" name="j_password" placeholder="Password">
                      </div>
                    </div>
                    <!-- Remember me checkbox and sign in button -->
                    <div class="form-group">
					<div class="col-lg-9 col-lg-offset-3">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox"> Remember me
                        </label>
						</div>
					</div>
					</div>
                        <div class="col-lg-9 col-lg-offset-3">
							<button type="submit" class="btn btn-danger">Sign in</button>
							<button type="reset" class="btn btn-default">Reset</button>
						</div>
                    <br />
                  </form>
				  
				</div>
                </div>
                    
                <div class="widget-foot">
                  Not Registred? <a href="#">Register here</a>
                </div>
            </div>  
      </div>
    </div>
  </div> 
</div>
	
		

<!-- JS --> 
<script type="text/javascript" src="<c:url value="/_js/jquery.js"/>"></script>
<script src="<c:url value="/_js/bootstrap.js"/>"></script>

</body>
</html>

src/main/webapp/views/loginFailed.jsp
<%@ page language="java" contentType="text/html; charset=US-ASCII"
    pageEncoding="US-ASCII"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
<title>Invalid Login</title>
</head>
<body>
	Try again! You inform a invalid login =/
	<a href="javascript:window.history.back()">Back</a>
</body>
</html>